Instagram feed
bits-and-bytes-association/rrc-bba-website pull request #56
Opened 2021-02-27 02:19 UTC by jtmar28

This is implementation is to add a Instagram feed to the Bits and Bits association front page.

2021-03-05 20:10 UTC, AyameU requested changes
I left a comment on one line of code that should be added back in, but otherwise it all looks good.

2021-03-05 20:10 UTC, AyameU commented on index.html
> -        <div w3-include-html="./header.html"></div>
Looks like this is missing from the updated code. Can you add it back in? Otherwise the header will be missing. :)

2021-03-05 20:47 UTC, jtmar28 reviewed
Made the changes Ayame 😂 Resolved header on main page and changed up the Instagram javascript file so that it gets open on new tab

2021-03-08 17:36 UTC, AyameU approved these changes
Awesome thank you! Looks great!

2021-03-08 17:36 UTC, merged